package main

import (
	"fmt"
	"log"
	"net/http"

	_ "api.nhn.no/admin/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
)

// @title NHN API Admin Service
// @description Various administrative functions for the API-gateway and k8s cluster
// @version 1.0
// @host localhost:8181
// @BasePath /admin/
func main() {
	router := mux.NewRouter()
	router.StrictSlash(true)

	router.HandleFunc("/admin/", SwaggerRedirect)
	router.HandleFunc("/admin/docs/", SwaggerRedirect)
	router.PathPrefix("/admin/docs").Handler(httpSwagger.WrapHandler)

	var portNumber = 8181
	fmt.Printf("Starting http listener on port %d ...\n", portNumber)
	log.Fatal(http.ListenAndServe(fmt.Sprintf(":%d", portNumber), router))
}

// SwaggerRedirect redirects HTTP request to Swagger docs
func SwaggerRedirect(w http.ResponseWriter, r *http.Request) {
	http.Redirect(w, r, "/admin/docs/index.html", http.StatusPermanentRedirect)
}
