basePath: /admin/
definitions:
  main.Service:
    properties:
      apibaseEndpoint:
        type: string
      name:
        type: string
      ociImage:
        type: string
      port:
        type: integer
    type: object
host: localhost:8181
info:
  contact: {}
  description: Various administrative functions for the API-gateway and k8s cluster
  title: NHN API Admin Service
  version: "1.0"
paths:
  /api/new:
    post:
      consumes:
      - application/json
      parameters:
      - description: Service info
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/main.Service'
      produces:
      - application/json
      responses:
        "201":
          description: ""
        "400":
          description: ""
swagger: "2.0"
